#!/bin/bash
echo "HI FROM POSTBUILD!"

# install R packages
echo 'local({r <- getOption("repos")
       r["CRAN"] <- "http://cran.r-project.org"
       options(repos=r)
})' > ~/.Rprofile

# some magic to install the R curl package, which is a prerequisite for other R packages.
wget https://cran.r-project.org/src/contrib/curl_4.2.tar.gz
R CMD INSTALL --configure-vars='INCLUDE_DIR=/usr/include/x86_64-linux-gnu/curl LIB_DIR=/usr/lib/x86_64-linux-gnu/curl' curl_4.2.tar.gz

Rscript -e "install.packages('httr')"
Rscript -e "install.packages('devtools')"
Rscript -e "install.packages('webutils')"
Rscript -e "install.packages('base64enc')"
# 'jug', our HTTP server, is now archived - install from source
Rscript -e "install.packages('https://cran.r-project.org/src/contrib/Archive/infuser/infuser_0.2.8.tar.gz')"
Rscript -e "install.packages('https://cran.r-project.org/src/contrib/Archive/jug/jug_0.1.7.tar.gz')"
Rscript -e "install.packages('arrow')"

# clone the master branch of wrattler
git clone https://github.com/wrattler/wrattler.git
cd ./wrattler/jupyterlab_wrattler/
jlpm run build
jupyter labextension install .
cd ../client
npm install http-server -g
cd ../..
pip install .

# link resources directory so that .py or .R resources can be served by the client
ln -s `pwd`/resources wrattler/client/public/
