#!/bin/bash
echo "HI FROM POSTBUILD!"
git clone --single-branch --branch feature/binder https://github.com/wrattler/wrattler.git
cd ./wrattler/jupyterlab_wrattler/
jlpm run build
jupyter labextension install .
cd ../client
npm install http-server -g
cd ../..
pip install .
